
version: '3'

services:
  cypress:
    image: cypress
    build:
      context: .
      dockerfile: Dockerfile.e2e
    environment:
      - CYPRESS_baseUrl=http://localhost:3000
    volumes:
      - ./tests/e2e/:/app/tests/e2e
      - ./tests/server:/app/tests/server
    shm_size: 1024M
    network_mode: host