version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: backend/.
    command: sh -c "python manage.py flush --noinput &&
                    python manage.py migrate &&
                    python manage.py loaddata test_data &&
                    python manage.py runserver 0.0.0.0:8000
                    "
    volumes:
      - type: bind
        source: ./backend/
        target: /app/backend/
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SECRET_KEY=django-insecure-2r0-em5**(by06f+&y5qj#3zs^s3^47hhci$o%p4fy@6(ttj(&
    depends_on:
      - db
  frontend:
    volumes:
      - type: bind
        source: ./frontend/
        target: /app/frontend/
    build: frontend/.
    command: npm run serve
    ports:
      - "8080:8080"
