# Generated by Django 4.0.1 on 2022-01-31 14:32

from django.db import migrations
import django.utils.timezone
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_tags_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayentry',
            options={'verbose_name_plural': 'Day entries'},
        ),
        migrations.AlterModelOptions(
            name='timeentry',
            options={'verbose_name_plural': 'Time entries'},
        ),
        migrations.AddField(
            model_name='timeentry',
            name='time_stamp',
            field=unixtimestampfield.fields.UnixTimeStampField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
