# Generated by Django 4.0.1 on 2022-01-31 14:46

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_dayentry_options_alter_timeentry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='time_stamp',
            field=unixtimestampfield.fields.UnixTimeStampField(default=0.0),
        ),
    ]
