# Generated by Django 4.0.1 on 2022-01-31 14:51

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_timeentry_time_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='time_stamp',
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='end_date',
            field=unixtimestampfield.fields.UnixTimeStampField(default=0.0),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='start_date',
            field=unixtimestampfield.fields.UnixTimeStampField(default=0.0),
        ),
    ]
