# Generated by Django 4.0.1 on 2022-02-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_timeentry_time_stamp_alter_timeentry_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='billable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='billable_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
