# Generated by Django 4.0.1 on 2022-02-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_dayentry_date_dayentry_time_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayentry',
            name='time_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
