# Generated by Django 4.0.1 on 2022-02-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_dayentry_time_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tracker.Tag'),
        ),
    ]
