# Generated by Django 4.0.1 on 2022-02-23 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_timeentry_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='billable',
        ),
        migrations.RemoveField(
            model_name='project',
            name='billable_rate',
        ),
        migrations.AddField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='time_total',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
