# Generated by Django 4.0.1 on 2022-02-23 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_remove_project_billable_remove_project_billable_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
    ]
