# Generated by Django 4.0.1 on 2022-02-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_remove_timeentry_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time_entries',
            field=models.ManyToManyField(related_name='project_time_entries', to='tracker.TimeEntry'),
        ),
    ]
